const CP = Object.freeze({
  PROJECT_NAME: 'Cuaderno del Profesor',
  NOTEBOOK_VERSION: '1.8.4',
  SCHEMA_VERSION: '11',
  TAB_COLORS: Object.freeze({
    GENERAL: '#546E7A',
    CONFIG: '#2E7D32',
    TRACKING: '#1565C0',
    EVALUATION: '#E65100',
    TUTORING: '#6A1B9A', // Reservado para la futura familia 7 Tutoría.
  }),
  SHEETS: Object.freeze({
    COVER: '0 Portada',
    CALENDAR: '1 Calendario',
    SCHEDULE: '2 Horario',
    STUDENTS: '3 Alumnado',
    CONFIG: '_CONFIG',
    CALENDAR_TYPES: '_CAL_TIPOS',
    CALENDAR_EVALUATIONS: '_CAL_EVALUACIONES',
    CALENDAR_DATES: '_FECHAS',
    CALENDAR_DATE_TYPES: '_CAL_FECHA_TIPOS',
    SCHEDULE_SLOTS: '_HOR_TRAMOS',
    SCHEDULE_ACTIVITIES: '_HOR_ACTIVIDADES',
    SCHEDULE_SESSIONS: '_HOR_SESIONES',
    MODULE_CONFIG: '_MOD_CONFIG',
    MODULE_PLAN: '_MOD_PLAN',
    META: '_META',
  }),
  CONFIG_KEYS: Object.freeze({
    ACADEMIC_YEAR: 'curso_academico',
    TEACHER: 'profesor',
    TEACHER_EMAIL: 'profesor_email',
    SCHOOL: 'centro',
    SCHOOL_ADDRESS: 'centro_direccion',
    SCHOOL_PHONE: 'centro_telefono',
    SCHOOL_EMAIL: 'centro_email',
    SCHOOL_WEB: 'centro_web',
    THEME_PRESET: 'tema_preset',
    THEME_PRIMARY: 'tema_primary',
    THEME_SECONDARY: 'tema_secondary',
    THEME_ACCENT: 'tema_accent',
  }),
  MENU: Object.freeze({
    NAME: '📘 Cuaderno del Profesor 📘',
    NEW_COURSE: '🆕 Preparar nuevo curso',
    INIT: '🔧 Reparar estructura',
    CONFIG: '⚙️ Configuración',
    GENERAL_DATA: '🪪 Configurar datos del docente y centro',
    CALENDAR_CONFIG: '📅 Configurar calendario',
    SCHEDULE_CONFIG: '🕒 Configurar horario',
    MODULES: '📚 Módulos',
    MODULE_CONFIG_CREATE: '🗓️ Crear configuración de módulo',
    MODULE_CONFIG_RECALCULATE: '🔄 Recalcular configuración del módulo',
    MODULE_TRACKING_CREATE: '📋 Crear seguimiento y evaluación',
    HELP: '❓ Ayuda',
  }),
  UI: Object.freeze({
    AUTHOR: 'Mikel Aingeru Jorge Soteras',
    AUTHOR_EMAIL: 'mjorgesote@educacion.navarra.es',
    INIT_CONFIRMATION_ID: 'confirm-initialize-notebook',
    INIT_PROCESS_ID: 'initialize-notebook',
    INIT_ACTION_ID: 'open-initialize-progress',
    NEW_COURSE_PROCESS_ID: 'prepare-new-course',
    CONFIRMATION_DIALOG_WIDTH: 460,
    CONFIRMATION_DIALOG_HEIGHT: 430,
    REPAIR_DIALOG_WIDTH: 520,
    REPAIR_DIALOG_HEIGHT: 460,
    GENERAL_CONFIG_DIALOG_WIDTH: 620,
    GENERAL_CONFIG_DIALOG_HEIGHT: 780,
    CALENDAR_CONFIG_DIALOG_WIDTH: 780,
    CALENDAR_CONFIG_DIALOG_HEIGHT: 820,
    SCHEDULE_CONFIG_DIALOG_WIDTH: 980,
    SCHEDULE_CONFIG_DIALOG_HEIGHT: 860,
    MODULE_CONFIG_DIALOG_WIDTH: 620,
    MODULE_CONFIG_DIALOG_HEIGHT: 650,
    MODULE_TRACKING_DIALOG_WIDTH: 620,
    MODULE_TRACKING_DIALOG_HEIGHT: 650,
    NEW_COURSE_DIALOG_WIDTH: 1000,
    NEW_COURSE_DIALOG_HEIGHT: 850,
    PROGRESS_DIALOG_WIDTH: 480,
    PROGRESS_DIALOG_HEIGHT: 560,
    CONFIRMATION_VARIANTS: Object.freeze({
      NORMAL: 'normal',
      WARNING: 'warning',
      DANGER: 'danger',
    }),
  }),
});
