const CP = Object.freeze({
  PROJECT_NAME: 'Cuaderno del Profesor',
  NOTEBOOK_VERSION: '1.2.0',
  SCHEMA_VERSION: '2',
  SHEETS: Object.freeze({
    COVER: '0 Portada',
    CONFIG: '_CONFIG',
    META: '_META',
  }),
  CONFIG_KEYS: Object.freeze({
    ACADEMIC_YEAR: 'curso_academico',
    TEACHER: 'profesor',
    TEACHER_EMAIL: 'profesor_email',
    SCHOOL: 'centro',
    SCHOOL_ADDRESS: 'centro_direccion',
    SCHOOL_PHONE: 'centro_telefono',
    SCHOOL_EMAIL: 'centro_email',
    SCHOOL_WEB: 'centro_web',
    THEME_PRESET: 'tema_preset',
    THEME_PRIMARY: 'tema_primary',
    THEME_SECONDARY: 'tema_secondary',
    THEME_ACCENT: 'tema_accent',
  }),
  MENU: Object.freeze({
    NAME: '📘 Cuaderno del Profesor 📘',
    INIT: '🔄 Inicializar / reparar estructura',
    CONFIG: '⚙️ Configuración',
    GENERAL_DATA: '👤 Datos generales',
    HELP: '❓ Ayuda',
  }),
  UI: Object.freeze({
    AUTHOR: 'Mikel Aingeru Jorge Soteras',
    AUTHOR_EMAIL: 'mjorgesote@educacion.navarra.es',
    INIT_CONFIRMATION_ID: 'confirm-initialize-notebook',
    INIT_PROCESS_ID: 'initialize-notebook',
    INIT_ACTION_ID: 'open-initialize-progress',
    CONFIRMATION_DIALOG_WIDTH: 460,
    CONFIRMATION_DIALOG_HEIGHT: 430,
    GENERAL_CONFIG_DIALOG_WIDTH: 620,
    GENERAL_CONFIG_DIALOG_HEIGHT: 780,
    PROGRESS_DIALOG_WIDTH: 480,
    PROGRESS_DIALOG_HEIGHT: 560,
    CONFIRMATION_VARIANTS: Object.freeze({
      NORMAL: 'normal',
      WARNING: 'warning',
      DANGER: 'danger',
    }),
  }),
});
