const CP = Object.freeze({
  PROJECT_NAME: 'Cuaderno del Profesor',
  NOTEBOOK_VERSION: '1.3.1',
  SCHEMA_VERSION: '6',
  SHEETS: Object.freeze({
    COVER: '0 Portada',
    CALENDAR: '1 Calendario',
    CONFIG: '_CONFIG',
    CALENDAR_TYPES: '_CAL_TIPOS',
    CALENDAR_EVALUATIONS: '_CAL_EVALUACIONES',
    CALENDAR_DATES: '_FECHAS',
    CALENDAR_DATE_TYPES: '_CAL_FECHA_TIPOS',
    SCHEDULE_SLOTS: '_HOR_TRAMOS',
    SCHEDULE_ACTIVITIES: '_HOR_ACTIVIDADES',
    SCHEDULE_SESSIONS: '_HOR_SESIONES',
    META: '_META',
  }),
  CONFIG_KEYS: Object.freeze({
    ACADEMIC_YEAR: 'curso_academico',
    TEACHER: 'profesor',
    TEACHER_EMAIL: 'profesor_email',
    SCHOOL: 'centro',
    SCHOOL_ADDRESS: 'centro_direccion',
    SCHOOL_PHONE: 'centro_telefono',
    SCHOOL_EMAIL: 'centro_email',
    SCHOOL_WEB: 'centro_web',
    THEME_PRESET: 'tema_preset',
    THEME_PRIMARY: 'tema_primary',
    THEME_SECONDARY: 'tema_secondary',
    THEME_ACCENT: 'tema_accent',
  }),
  MENU: Object.freeze({
    NAME: '📘 Cuaderno del Profesor 📘',
    NEW_COURSE: '🆕 Preparar nuevo curso',
    INIT: '🔄 Inicializar / reparar estructura',
    CONFIG: '⚙️ Configuración',
    GENERAL_DATA: '👤 Datos generales',
    CALENDAR_CONFIG: '📅 Configurar calendario',
    SCHEDULE_CONFIG: '🕒 Configurar horario',
    HELP: '❓ Ayuda',
  }),
  UI: Object.freeze({
    AUTHOR: 'Mikel Aingeru Jorge Soteras',
    AUTHOR_EMAIL: 'mjorgesote@educacion.navarra.es',
    INIT_CONFIRMATION_ID: 'confirm-initialize-notebook',
    INIT_PROCESS_ID: 'initialize-notebook',
    INIT_ACTION_ID: 'open-initialize-progress',
    NEW_COURSE_CONFIRMATION_ID: 'confirm-prepare-new-course',
    NEW_COURSE_PROCESS_ID: 'prepare-new-course',
    NEW_COURSE_ACTION_ID: 'open-new-course-wizard',
    CONFIRMATION_DIALOG_WIDTH: 460,
    CONFIRMATION_DIALOG_HEIGHT: 430,
    GENERAL_CONFIG_DIALOG_WIDTH: 620,
    GENERAL_CONFIG_DIALOG_HEIGHT: 780,
    CALENDAR_CONFIG_DIALOG_WIDTH: 780,
    CALENDAR_CONFIG_DIALOG_HEIGHT: 820,
    SCHEDULE_CONFIG_DIALOG_WIDTH: 980,
    SCHEDULE_CONFIG_DIALOG_HEIGHT: 860,
    NEW_COURSE_DIALOG_WIDTH: 640,
    NEW_COURSE_DIALOG_HEIGHT: 760,
    PROGRESS_DIALOG_WIDTH: 480,
    PROGRESS_DIALOG_HEIGHT: 560,
    CONFIRMATION_VARIANTS: Object.freeze({
      NORMAL: 'normal',
      WARNING: 'warning',
      DANGER: 'danger',
    }),
  }),
});
