const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const context = {};
vm.createContext(context);
vm.runInContext(fs.readFileSync('Students.gs', 'utf8'), context);
const normalize = context.normalizeStudentReacaValue_;
assert.strictEqual(normalize(true), true);
assert.strictEqual(normalize(false), false);
assert.strictEqual(normalize('TRUE'), true);
assert.strictEqual(normalize(' false '), false);
assert.strictEqual(normalize(''), false);
assert.strictEqual(normalize(null), false);
assert.strictEqual(normalize('REACA'), null);
assert.strictEqual(normalize(1), null);
const source = fs.readFileSync('Students.gs', 'utf8');
assert.ok(source.includes('.insertCheckboxes()'));
assert.ok(source.includes("row.slice(0, 3).every"));
console.log('REACA checkbox normalization and valid-row checks passed');
